version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PGUSER:-ruti}
      POSTGRES_PASSWORD: ${PGPASSWORD:-rutidev}
      POSTGRES_DB: ${PGDATABASE:-leaderboard}
    # ports:
    #   - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./server/models/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./server/models/seed.js:/docker-entrypoint-initdb.d/02_seed.js:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PGUSER:-ruti} -d ${PGDATABASE:-leaderboard}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  server:
    build: ./server
    env_file:
      - ./server/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - "3033:80"

volumes:
  pg_data:
